matches:
  - trigger: ";ip"
    replace: "{{ip}}"
    vars:
      - name: ip
        type: shell
        params:
          cmd: "curl 'https://icanhazip.com'"
  - trigger: ";proof"
    replace: "{{c99::::proof}}"
  - trigger: ";ml"
    replace: "::more/less"
  - trigger: ";hl"
    replace: "::higher/lower"
  - trigger: ";id"
    replace: "::increases/decreases"
