keys:
  - &admin age1hf2zuvuwccu5r5u8rj5yuqapxkdjr8pnsqg6ehsgr5l7hr6meqrquqq0nx
  - &root-desktop age1c0efwwd98587gdu7yyuhzhgpzg3j7mvmrynlpzvu5dgrq6dqu3tsf9pmnp
  - &yiheng-desktop age1z6jpfald6ktxa3sq86qp6vr0fefrl6fyc54saztf086mgakh797smq80hg
  - &root-goon age1qtrx64maz2xhjv2r46ya2q6w9utqclxmvkxjd00racxwnntey3lsm2m226
  - &yiheng-goon age12pza2uxdg43603zyscjamm0lnrgsjj8z7pkrzv6d9fefgaz0f3zq60lutl
  - &yiheng-X1C12 age1daedc94752j8jsu5d27kja2g0fy3ydk6lq878xn0zncvnydcuy8su6vr2e
  - &root-X1C12 age1egapxm7h9ll4969ulta7pxtgf2kx3q6tddtzgtzmqx8n8rstx92s2keqjz
creation_rules:
  - path_regex: ^secrets/root/desktop/.+$
    key_groups:
      - age:
          - *admin
          - *root-desktop
  - path_regex: ^secrets/root/[^/]+$
    key_groups:
      - age:
          - *admin
          - *root-desktop
          - *root-goon
          - *root-X1C12
  - path_regex: ^secrets/home/[^/]+$
    key_groups:
      - age:
          - *admin
          - *yiheng-desktop
          - *yiheng-goon
          - *yiheng-X1C12
  - path_regex: ^secrets/[^/]+$
    key_groups:
      - age:
          - *admin
          - *root-desktop
          - *root-goon
          - *root-X1C12
          - *yiheng-desktop
          - *yiheng-goon
          - *yiheng-X1C12
  - path_regex: ^secrets/.+$
    key_groups:
      - age:
          - *admin
