pragma Singleton
import Quickshell

Singleton {
    readonly property string rosewater: "#f5e0dc"
    readonly property string flamingo: "#f2cdcd"
    readonly property string pink: "#f5c2e7"
    readonly property string mauve: "#cba6f7"
    readonly property string red: "#f38ba8"
    readonly property string maroon: "#eba0ac"
    readonly property string peach: "#fab387"
    readonly property string yellow: "#f9e2af"
    readonly property string green: "#a6e3a1"
    readonly property string teal: "#94e2d5"
    readonly property string sky: "#89dceb"
    readonly property string sapphire: "#74c7ec"
    readonly property string blue: "#89b4fa"
    readonly property string lavender: "#b4befe"
    readonly property string text: "#cdd6f4"
    readonly property string subtext1: "#bac2de"
    readonly property string subtext0: "#a6adc8"
    readonly property string overlay2: "#9399b2"
    readonly property string overlay1: "#7f849c"
    readonly property string overlay0: "#6c7086"
    readonly property string surface2: "#585b70"
    readonly property string surface1: "#45475a"
    readonly property string surface0: "#313244"
    readonly property string base: "#1e1e2e"
    readonly property string mantle: "#181825"
    readonly property string crust: "#11111b"
}
