[shell]
font_family = "Iosevka Custom"
screen_time_enabled = true

[shell.animation]
enabled = false

[shell.panel]
control_center_placement = "floating"
open_near_click_control_center = true
open_near_click_session = true
session_placement = "floating"
session_position = "center"
wallpaper_placement = "floating"

[shell.screen_corners]
enabled = true
