name: "nix flake check"

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: lazy-trees = true
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check --no-build --show-trace
